---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sign-oot-kmods
  labels:
    app.kubernetes.io/version: "0.0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Task to sign OOT kernel modules using the internal signing server
  params:
    - name: dataPath
      type: string
      description: Path to the data JSON in the data workspace
    - name: signedKmodsPath
      type: string
      description: Path where the kernel modules are stored in the workspace.
    - name: kerberosRealm
      type: string
      description: Name of the key used to sign the kernel modules
    - name: signingAuthor
      type: string
      description: Human name responsible for the signing process
    - name: checksumFingerprint
      type: string
      description: Secret containing the host key database for SSH the server running signing
    - name: checksumKeytab
      type: string
      description: Secret containing keytab file for the Kerberos user / server
    - name: signing-secret
      type: string
      description: Secret containing the fields signHost, SignKey and SignUser 
  volumes:
    - name: bs-keytab
      secret:
        secretName: $(params.checksumKeytab)    
    - name: checksum-fingerprint
      secret:
        secretName: $(params.checksumFingerprint)
  workspaces:
    - name: kmods
      description: The workspace where unsigned kernel modules are.
  steps:
    - name: sign-files
      image: quay.io/konflux-ci/release-service-utils:0f82be4be43294b6a96846d87ef7f7c0b9e34267
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: 250m 
      volumeMounts:
        - name: checksum-fingerprint
          mountPath: "/etc/sec-checksum"
          readOnly: true
        - name: bs-keytab
          mountPath: "/etc/sec-keytab"
          readOnly: true        
      env:
        - name: signKey
          valueFrom:
            secretKeyRef:
              name: $(params.signing-secret)
              key: signKey
        - name: signHost
          valueFrom:
            secretKeyRef:
              name: $(params.signing-secret)
              key: signHost
        - name: signUser
          valueFrom:
            secretKeyRef:
              name: $(params.signing-secret)
              key: signUser
      script: |
        #!/usr/bin/env bash
        set -eux
        
        signedKmodsPath="$(params.signedKmodsPath)"
        signingAuthor="$(params.signingAuthor)"
        # Remove newline in signing variables 
        signUser="${signUser//$'\n'/}"
        signHost="${signHost//$'\n'/}"
         
        echo "Signing OOT modules from $(workspaces.kmods.path)$signedKmodsPath.."
        SIGNED_KMODS_PATH="$(workspaces.kmods.path)/$signedKmodsPath"
        SSH_OPTS=(
          -o UserKnownHostsFile=/root/.ssh/known_hosts
          -o GSSAPIAuthentication=yes
          -o GSSAPIDelegateCredentials=yes
        )
        sign_kmods() {
             signing_author="$signingAuthor"
             export signing_author
             export signKey
             echo "Executing SSH command to sign OOT kernel module for PipelineRun"
             ssh "${SSH_OPTS[@]}" "${signUser}@${signHost}" 'export KEY="'"${signKey}"'"; bash -s' <<'EOF'
             echo "Signing OOT kernel modules using $KEY key..."
             for kmod in ~/kmods/*.ko; do
                 if [ -f "$kmod" ]; then
                     echo "Remote: Signing kernel module $kmod"
                     rh-signing-client --key "$KEY" --onbehalfof "${signing_author}" --lkmsign "$kmod"
                     if [ $? -ne 0 ]; then
                         echo "Remote: ERROR failed to sign $kmod"
                         exit 1
                     fi
                 else
                     echo "Remote: Skipping entry $kmod (not a regular file or no .ko files found)"
                 fi
             done
             echo "Remote: Finished signing process for PR"
        EOF
        }
        KRB5CCNAME=FILE:/tmp/krb5cc_$(id -u)
        export KRB5CCNAME
        kinit -kt /etc/sec-keytab/keytab-build-and-sign.keytab "${signUser}@$(params.kerberosRealm)"

        mkdir -p /root/.ssh
        chmod 700 /root/.ssh
        cp /etc/sec-checksum/checksumFingerprint /root/.ssh/known_hosts
        chmod 600 root/.ssh/known_hosts

        cd "$SIGNED_KMODS_PATH" || exit 1
        # Copy unsigned kmods to signing server
        ssh "${SSH_OPTS[@]}" "${signUser}@${signHost}" "mkdir -p ~/kmods"
        scp "${SSH_OPTS[@]}" "${SIGNED_KMODS_PATH}"/*.ko "${signUser}@${signHost}:~/kmods/"
        # Sign kmods
        sign_kmods
        # Copy back signed kmods to workspace
        scp "${SSH_OPTS[@]}" "${signUser}@${signHost}:~/kmods/*.ko" "${SIGNED_KMODS_PATH}"/
