---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-oot-kmods 
  labels:
    app.kubernetes.io/version: "0.0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Task to upload OOT kernel modules to private vendor repo
  params:
    - name: signedKmodsPath 
      type: string
      description: Path where the kernel modules are stored in the workspace
    - name: vendor
      type: string
      description: vendor of the kernel modules
    - name: artifactRepoUrl
      type: string
      description: Repository URL where the signed modules will be pushed
    - name: artifactBranch
      type: string
      default: main
      description: Specific branch in the repository
    - name: artifactRepoToken
      type: string
      description: Secret containing the Project Access Token for the artifact repos
  workspaces:
    - name: signed-kmods
      description: The workspace where unsigned kernel modules are.
  steps:
    - name: push-signed-files
      image: quay.io/konflux-ci/release-service-utils:0f82be4be43294b6a96846d87ef7f7c0b9e34267
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: 250m 
      env:
        - name: PUSH_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.artifactRepoToken)
              key: gitlab-gr-maintenance-token
      script: |
        #!/usr/bin/env sh
        SIGNED_KMODS_PATH="$(workspaces.signed-kmods.path)/$(params.signedKmodsPath)"
        REPO_URL="$(params.artifactRepoUrl)"
        echo "PATH: ${SIGNED_KMODS_PATH} to ${REPO_URL}"
        mkdir -p "${SIGNED_KMODS_PATH}"
        cd "${SIGNED_KMODS_PATH}" || exit 1
        git lfs install

        ## Add token to URL
        PUSH_TOKEN_CLEAN=$(printf "%s" "$PUSH_TOKEN" | tr -d '\n')
        GIT_URL_WITH_AUTH="https://gitlab-ci-token:${PUSH_TOKEN_CLEAN}@${REPO_URL}"
        
        git clone "$GIT_URL_WITH_AUTH" local-artifacts
        # Create directory with vendor/versions and move signed modules there
        # shellcheck source=/dev/null
        . ./envfile
        mkdir -p "local-artifacts/${DRIVER_VENDOR}_${DRIVER_VERSION}_${KERNEL_VERSION}" 
        mv -- *.ko "local-artifacts/${DRIVER_VENDOR}_${DRIVER_VERSION}_${KERNEL_VERSION}/"
        rm envfile
       
        cd local-artifacts || exit 1
        git checkout main
        git config --global user.email "partner-accelerators@konflux-ci.redhat.com"
        git config --global user.name "Partner Accelerators CI Bot"
  
        git add .
        git commit -m "Automated push from Build and Sign pipeline"
        git push -u origin main
